=== ralscha/attic/attic/misc3/xmltests/example.dtd
<!-- DTD for Recipe XML -->

<!ELEMENT Recipe (Name, Description?, Ingredients?, Instructions?)>

<!ELEMENT Name (#PCDATA)>

<!ELEMENT Description (#PCDATA)>

<!ELEMENT Ingredients (Ingredient)*>

<!ELEMENT Ingredient (Qty, Item)>
<!ATTLIST Ingredient
	vegetarian CDATA "true">

<!ELEMENT Qty (#PCDATA)>
<!ATTLIST Qty
	unit CDATA #IMPLIED>

<!ELEMENT Item (#PCDATA)>
<!ATTLIST Item
	optional CDATA "0">

<!ELEMENT Instructions (Step)+>

<!ELEMENT Step (#PCDATA)>

=== ralscha/attic/attic/misc3/xmltests/example3.xml
<?xml version="1.0"?>

<!DOCTYPE Recipe SYSTEM "example.dtd">

<Recipe>
   <Name>Nanner Pah</Name>
   <Description>The famous "Nanner Pah", which is how an old
Kentucky grandma I knew said, "Banana Pie". Mmm-mm!</Description>
   <Ingredients>
      <Ingredient>
         <Qty unit="box">1</Qty>
         <Item>Nilla wafers (vanilla cookies)</Item>
      </Ingredient>
      <Ingredient>
         <Qty unit="pkg">1</Qty>
         <Item>instant vanilla pudding</Item>
      </Ingredient>
      <Ingredient>
         <Qty>3</Qty>
         <Item>bananas, not too ripe</Item>
      </Ingredient>
      <Ingredient>
         <Qty unit="container">1</Qty>
         <Item>Cool-Whip</Item>
      </Ingredient>
   </Ingredients>
   <Instructions>
      <Step>
Fix the vanilla pudding.
      </Step>
      <Step>
Line a glass baking dish with Nilla Wafers.
      </Step>
      <Step>
Put a layer of pudding over the wafers. Use maybe half the pudding.
      </Step>
      <Step>
Slice half of the bananas over the pudding.
      </Step>
      <Step>
Add a layer of Cool-Whip.
      </Step>
      <Step>
Repeat all four layers, finishing with Cool Whip.
      </Step>
      <Step>
If you've got anything left over, don't give it to the dog, 'cuz
it'll make him sick. And if he gits sick, you're the one to clean
it up!
      </Step>
   </Instructions>
</Recipe>

=== ralscha/attic/attic/misc3/xmltests/example2.xml
<?xml version="1.0"?>

<!DOCTYPE Recipe SYSTEM "example.dtd">

<!-- This document has some errors that a validating parser will catch -->

<Recipe>
   <Name>Lime Jello Marshmallow Cottage Cheese Surprise</Name>
   <Description>My grandma's favorite (may she rest in peace.)</Description>
   <Ingredients>
      <Ingredient vegetarian="false">
         <Qty unit="box">1</Qty>
         <Item>lime gelatin</Item>
      </Ingredient>
      <Ingredient vegetarian="false">
         <Qty unit="g">500</Qty>
         <Item>multicolored tiny marshmallows</Item>
      </Ingredient>
      <Ingredient vegetarian="false">
      <!-- Note that here, Qty and Item are reversed -->
         <Item>Cottage cheese</Item>
         <Qty unit="ml">500</Qty>
      </Ingredient>
      <Ingredient>
         <Qty unit="dash"/>
         <Item optional="true">Tabasco sauce</Item>
      </Ingredient>
      <Ingredient>
      <!-- Note that here, Qty is missing -->
         <Item>Horseradish to taste</Item>
      </Ingredient>
   </Ingredients>
   <Instructions>
      <Step>
Prepare lime gelatin according to package instructions.
      </Step>
      <Step>
Come to your senses.
      </Step>
      <Step>
Discard all ingredients.
      </Step>
      <Step>
Go to Ben &amp; Jerry's.
      </Step>
   </Instructions>
</Recipe>
